In [29]:
import matplotlib.pyplot as plt
import numpy as np
import arviz as az
from cmdstanpy import CmdStanModel

# Generowanie danych

In [2]:
N = 100

model1 = CmdStanModel(stan_file='code_1.stan')
sample1 = model1.sample({'N': N})

model2 = CmdStanModel(stan_file='code_2.stan')
sample2 = model2.sample({'N': N})

INFO:cmdstanpy:found newer exe file, not recompiling
INFO:cmdstanpy:CmdStan start procesing
chain 1 |          | 00:00 Status



chain 1 |████▌     | 00:00 Iteration: 800 / 1000 [ 80%]  (Sampling)

chain 1 |██████████| 00:00 Sampling completed
chain 2 |██████████| 00:00 Sampling completed
chain 3 |██████████| 00:00 Sampling completed
chain 4 |██████████| 00:00 Sampling completed

INFO:cmdstanpy:CmdStan done processing.

INFO:cmdstanpy:found newer exe file, not recompiling
INFO:cmdstanpy:CmdStan start procesing
chain 1 |          | 00:00 Status



chain 1 |█▊        | 00:00 Iteration: 200 / 1000 [ 20%]  (Sampling)

chain 1 |███▏      | 00:00 Iteration: 500 / 1000 [ 50%]  (Sampling)


chain 1 |████▌     | 00:00 Iteration: 800 / 1000 [ 80%]  (Sampling)


chain 1 |██████████| 00:00 Sampling completed
chain 2 |██████████| 00:00 Sampling completed
chain 3 |██████████| 00:00 Sampling completed
chain 4 |██████████| 00:00 Sampling completed

INFO:cmdstanpy:CmdStan done processing.

In [3]:
sample1.summary()

         Mean   MCSE        StdDev    5%     50%   95%   N_Eff  N_Eff/s  R_hat
name
lp__    0.000    NaN  0.000000e+00  0.00  0.0000  0.00     NaN      NaN    NaN
theta   0.010    NaN  2.400000e-16  0.01  0.0100  0.01     NaN      NaN    NaN
y[1]    0.120  0.029  1.800000e+00 -1.70  0.0220  1.80  3946.0  10065.0    1.0
y[2]    0.076  0.026  1.600000e+00 -1.60  0.0054  1.70  3868.0   9868.0    1.0
y[3]    0.110  0.026  1.600000e+00 -1.70  0.0270  1.70  3902.0   9955.0    1.0
...       ...    ...           ...   ...     ...   ...     ...      ...    ...
y[96]   0.100  0.029  1.800000e+00 -1.60 -0.0150  1.80  3955.0  10090.0    1.0
y[97]   0.100  0.029  1.800000e+00 -1.70  0.0200  1.70  3787.0   9662.0    1.0
y[98]   0.098  0.029  1.800000e+00 -1.70  0.0049  1.80  4020.0  10256.0    1.0
y[99]   0.055  0.022  1.400000e+00 -1.60  0.0013  1.70  3922.0  10004.0    1.0
y[100]  0.120  0.030  1.900000e+00 -1.60  0.0100  1.70  4132.0  10540.0    1.0

[102 rows x 9 columns]

In [4]:
sample2.summary()

          Mean   MCSE  StdDev   5%      50%  95%   N_Eff  N_Eff/s  R_hat
name
lp__    0.0000    NaN     0.0  0.0  0.00000  0.0     NaN      NaN    NaN
X[1,1] -0.0110  0.016     1.0 -1.7  0.01600  1.6  4212.0   2763.0    1.0
X[1,2] -0.0022  0.016     1.0 -1.6 -0.00430  1.7  3925.0   2575.0    1.0
X[1,3] -0.0150  0.016     1.0 -1.7  0.00085  1.6  3789.0   2486.0    1.0
X[2,1] -0.0059  0.016     1.0 -1.6 -0.03000  1.6  3912.0   2567.0    1.0
...        ...    ...     ...  ...      ...  ...     ...      ...    ...
y[96]   0.0140  0.041     2.5 -4.0 -0.02600  4.1  3604.0   2365.0    1.0
y[97]  -0.0220  0.040     2.5 -4.0 -0.07500  4.1  3947.0   2590.0    1.0
y[98]  -0.0320  0.040     2.5 -4.1 -0.02600  4.2  3950.0   2592.0    1.0
y[99]  -0.0190  0.040     2.5 -4.2  0.01600  4.1  3926.0   2576.0    1.0
y[100]  0.0530  0.042     2.5 -4.1  0.11000  4.1  3533.0   2318.0    1.0

[404 rows x 9 columns]

# Compare normal and student models for data from first file

In [26]:
sample1.stan_variable('y').shape[1]

100

In [28]:
y = sample1.stan_variable('y')
inputY = []
for i in range(y.shape[1]):
    OneY = []
    for j in range(y.shape[0]):
        OneY.append(y[j, i])
    inputY.append(np.mean(OneY))

model3 = CmdStanModel(stan_file='code_3.stan')
sample3 = model3.sample({'N': N, 'y':inputY })

model4 = CmdStanModel(stan_file='code_4.stan')
sample4 = model4.sample({'N': N, 'y': inputY})

INFO:cmdstanpy:found newer exe file, not recompiling
INFO:cmdstanpy:CmdStan start procesing

100

chain 1 |          | 00:00 Status



chain 1 |██████▊   | 00:00 Iteration: 1200 / 2000 [ 60%]  (Sampling)

chain 1 |██████████| 00:00 Sampling completed
chain 2 |██████████| 00:00 Sampling completed
chain 3 |██████████| 00:00 Sampling completed
chain 4 |██████████| 00:00 Sampling completed

INFO:cmdstanpy:CmdStan done processing.

INFO:cmdstanpy:compiling stan file E:\Obiekty 3D\GitHub\Data-Analytics-2022---Jan-Sawicki\Labolatory 07\code_4.stan to exe file E:\Obiekty 3D\GitHub\Data-Analytics-2022---Jan-Sawicki\Labolatory 07\code_4.exe
INFO:cmdstanpy:compiled model executable: E:\Obiekty 3D\GitHub\Data-Analytics-2022---Jan-Sawicki\Labolatory 07\code_4.exe
INFO:cmdstanpy:CmdStan start procesing
chain 1 |          | 00:00 Status


chain 1 |█████▉    | 00:00 Iteration: 1001 / 2000 [ 50%]  (Sampling)


chain 1 |██████████| 00:00 Sampling completed
chain 2 |██████████| 00:00 Sampling completed
chain 3 |██████████| 00:00 Sampling completed
chain 4 |██████████| 00:00 Sampling completed

INFO:cmdstanpy:CmdStan done processing.

In [30]:
sample3.summary()

,Mean,MCSE,StdDev,5%,50%,95%,N_Eff,N_Eff/s,R_hat
name,,,,,,,,,
lp__,230.000,0.024000,1.0000,220.000,230.000,230.000,1800.0,1700.0,1.0
sigma,0.026,0.000046,0.0019,0.023,0.026,0.029,1600.0,1500.0,1.0
mu,0.100,0.000043,0.0027,0.097,0.100,0.110,3900.0,3600.0,1.0
log_lik[1],2.400,0.001500,0.0830,2.300,2.400,2.600,3122.0,2935.0,1.0
log_lik[2],2.300,0.001600,0.0970,2.100,2.300,2.400,3865.0,3633.0,1.0
...,...,...,...,...,...,...,...,...,...
y_hat[96],0.100,0.000420,0.0270,0.058,0.100,0.150,4073.0,3828.0,1.0
y_hat[97],0.100,0.000420,0.0260,0.058,0.100,0.150,3898.0,3664.0,1.0
y_hat[98],0.100,0.000430,0.0270,0.057,0.100,0.140,3796.0,3567.0,1.0
y_hat[99],0.100,0.000430,0.0260,0.059,0.100,0.140,3634.0,3415.0,1.0
y_hat[100],0.100,0.000410,0.0260,0.058,0.100,0.140,4092.0,3846.0,1.0

In [31]:
sample4.summary()

,Mean,MCSE,StdDev,5%,50%,95%,N_Eff,N_Eff/s,R_hat
name,,,,,,,,,
lp__,220.000,0.027000,1.2000,210.000,220.000,220.000,2100.0,2100.0,1.0
sigma,0.020,0.000036,0.0020,0.017,0.020,0.024,3100.0,3200.0,1.0
mu,0.099,0.000040,0.0029,0.095,0.099,0.100,5100.0,5200.0,1.0
nu,2.100,0.001800,0.0970,1.900,2.100,2.200,2900.0,2900.0,1.0
log_lik[1],2.200,0.002100,0.1500,1.900,2.200,2.400,4922.0,4967.0,1.0
...,...,...,...,...,...,...,...,...,...
y_hat[96],0.100,0.000920,0.0580,0.041,0.099,0.160,3921.0,3957.0,1.0
y_hat[97],0.100,0.000900,0.0560,0.045,0.100,0.160,3863.0,3898.0,1.0
y_hat[98],0.100,0.000840,0.0500,0.043,0.100,0.160,3527.0,3559.0,1.0
y_hat[99],0.098,0.000960,0.0610,0.037,0.100,0.150,3996.0,4032.0,1.0
y_hat[100],0.099,0.001100,0.0660,0.044,0.100,0.160,3477.0,3508.0,1.0

In [39]:
dat3 = sample3.draws_pd()
dat4 = sample4.draws_pd()

compare_dict = {"Model stan_3": dat3, "Model stan_4": dat4}
az.compare(compare_dict)

c:\Users\Jasio\anaconda3\lib\site-packages\arviz\stats\stats.py:145: UserWarning: The default method used to estimate the weights for each model,has changed from BB-pseudo-BMA to stacking
  warnings.warn(

ValueError: Can only convert xarray dataarray, xarray dataset, dict, netcdf filename, numpy array, pystan fit, pymc3 trace, emcee fit, pyro mcmc fit, numpyro mcmc fit, cmdstan fit csv filename, cmdstanpy fit to InferenceData, not DataFrame